stages:
  - package
  - deploy

.ko:
  stage: package
  image: alpine:edge
  variables:
    KO_DOCKER_REPO: $CI_REGISTRY_IMAGE
  before_script:
    - echo https://dl-cdn.alpinelinux.org/alpine/edge/testing/ >> /etc/apk/repositories
    - apk add ko go
    - ko login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - ko build -B -t $CI_PIPELINE_ID $IMPORT_PATH

package:manager:
  extends: .ko
  variables:
    IMPORT_PATH: ./cmd/manager

package:dappy:
  extends: .ko
  variables:
    IMPORT_PATH: ./cmd/dappy

deploy:
  stage: deploy
  image: alpine:edge
  only: [main]
  before_script:
    - apk add kubectl gettext
    - kubectl config use-context aic/infra/agent:aic
  script:
    - envsubst < config/aic/kustomization.yaml.envsubst > config/aic/kustomization.yaml
    - kubectl apply -k config/aic
    - |
      kubectl create secret docker-registry gitlab-registry \
        --docker-server="$CI_REGISTRY" --docker-username="$CI_DEPLOY_USER" \
        --docker-password="$CI_DEPLOY_PASSWORD" --dry-run=client -o yaml \
        | kubectl -n fluorescence-system apply -f -
