---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fluorescence-aic-cs-nycu-edu-tw-v1alpha1-apiset
  failurePolicy: Fail
  name: vapiset.kb.io
  rules:
  - apiGroups:
    - fluorescence.aic.cs.nycu.edu.tw
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apisets
  sideEffects: None
