# permissions for end users to view apisets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: apiset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-cgi
    app.kubernetes.io/part-of: kube-cgi
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: apiset-viewer-role
rules:
- apiGroups:
  - kube-cgi.aic.cs.nycu.edu.tw
  resources:
  - apisets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kube-cgi.aic.cs.nycu.edu.tw
  resources:
  - apisets/status
  verbs:
  - get
