# permissions for end users to edit apisets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: apiset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fluorescence
    app.kubernetes.io/part-of: fluorescence
    app.kubernetes.io/managed-by: kustomize
  name: apiset-editor-role
rules:
- apiGroups:
  - fluorescence.aic.cs.nycu.edu.tw
  resources:
  - apisets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluorescence.aic.cs.nycu.edu.tw
  resources:
  - apisets/status
  verbs:
  - get
