---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dappy
rules:
- apiGroups:
  - fluorescence.aic.cs.nycu.edu.tw
  resources:
  - apisets
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - get
  - list
  - watch
