apiVersion: kube-cgi.aic.cs.nycu.edu.tw/v1alpha1
kind: APISet
metadata:
  labels:
    app.kubernetes.io/name: apiset
    app.kubernetes.io/instance: apiset-sample
    app.kubernetes.io/part-of: kube-cgi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-cgi
  name: apiset-sample
spec:
  # TODO(user): Add fields here
